#!/usr/bin/env bash
# Regenerate the checked-in typify output from the pinned herdr schema.
#
# Reproducible by construction: the same pinned schema + the same typify version
# produce byte-identical src/generated/*.rs. CI re-runs this and fails on any
# diff, so a herdr protocol bump surfaces as a reviewable change here (and, where
# a field type moved, a compile break downstream) rather than a silent
# runtime mis-decode.
#
# Requires: python3, cargo-typify, rustfmt (see flake devShell). typify's raw
# output is run through the PINNED rustfmt so the committed generated code is
# rustfmt-canonical: `cargo fmt` is then idempotent on it and regeneration stays
# byte-for-byte deterministic (rustfmt is deterministic per version).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
schema="$here/schema/herdr-api.schema.json"
out="$here/src/generated"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

subs=(error_response event request subscription_event success_response)
for name in "${subs[@]}"; do
  python3 "$here/scripts/flatten.py" "$schema" "$name" >"$tmp/$name.json"
  cargo-typify typify -d PartialEq "$tmp/$name.json" -o "$out/$name.rs"
  rustfmt --edition 2021 "$out/$name.rs"
done

# protocol.rs — lift protocol/schema_version from the pinned schema so the client
# can fail loud against an incompatible server. Kept in the generated set so a
# protocol bump shows up in the regen diff.
proto="$(python3 -c "import json;print(json.load(open('$schema'))['protocol'])")"
schemaver="$(python3 -c "import json;print(json.load(open('$schema'))['schema_version'])")"
cat >"$out/protocol.rs" <<EOF
// @generated by scripts/regen.sh from schema/herdr-api.schema.json — DO NOT EDIT.
//
// These constants are lifted from the pinned schema's top-level \`protocol\` and
// \`schema_version\` fields so the client can fail loud against an incompatible
// herdr server instead of silently mis-decoding.

/// herdr wire protocol version these types were generated against.
pub const PROTOCOL: u32 = ${proto};

/// Version of herdr's schema *container* format (the \`schemas\` envelope), not
/// the wire protocol.
pub const SCHEMA_VERSION: u32 = ${schemaver};
EOF
rustfmt --edition 2021 "$out/protocol.rs"

echo "regenerated ${#subs[@]} sub-schemas + protocol.rs (protocol ${proto}, schema_version ${schemaver})"
