//! Typed Rust client for [herdr](https://github.com/ogulcancelik/herdr)'s
//! socket API.
//!
//! herdr is an agent-aware terminal multiplexer whose CLI is a thin wrapper over
//! a newline-delimited JSON socket protocol. This crate is the typed equivalent
//! of that CLI: the request/response types in [`generated`] are produced from
//! herdr's own published JSON Schema (`herdr api schema --json`), and a small
//! hand-written transport (see `transport`, added incrementally) speaks the
//! socket directly.
//!
//! # Why generated + checked in
//!
//! The types under [`generated`] are regenerated by `scripts/regen.sh` and
//! **committed**, not built at compile time. That keeps downstream (Nix) builds
//! hermetic and offline, and makes any herdr protocol change show up as a
//! reviewable diff or a compile error rather than a silent runtime mis-decode.
//! [`PROTOCOL`] records the herdr `protocol` version the checked-in types were
//! generated against, so a client can refuse an incompatible server.
//!
//! # License boundary
//!
//! herdr is AGPL-3.0; this crate is MIT OR Apache-2.0 and contains only
//! schema-generated types plus a hand-written transport — no herdr
//! implementation source. It is a separate program speaking herdr's documented
//! protocol, which is the whole point of keeping it a distinct crate.

pub mod error;
pub mod generated;
pub mod methods;
pub mod transport;

pub use error::{Error, Result};
pub use generated::protocol::{PROTOCOL, SCHEMA_VERSION};
pub use transport::{Connection, Pong};

// Re-export the per-sub-schema modules at the crate root for ergonomics.
pub use generated::{error_response, event, request, subscription_event, success_response};
